services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DOCKERIZED=1
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery
      - neo4j
    command: >
      sh -c "
        alembic upgrade head &&
       python -m app.database.seeder.run_seeder &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: holidaynepal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" 

  redis:
    image: redis:7
    restart: always
    container_name: holidaynepal-redis 
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: holidaynepal-celery
    restart: always
    command: >
      sh -c "celery -A app.core.celery_tasks.c_app worker --loglevel=info"
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEFAULT_REGION=us-east-1
      - LOCALSTACK_VOLUME_DIR=/var/lib/localstack
    volumes:
      - ./localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

    command: >
      sh -c "
        sleep 10 &&
        awslocal s3 mb s3://holidaynepal &&
        echo 'Bucket holidaynepal created' &&
        exec localstack start
      "

  neo4j:
    image: neo4j:5.19
    container_name: holidaynepal-neo4j
    restart: always
    ports:
      - "7474:7474"   # Browser UI
      - "7687:7687"   # Bolt protocol for drivers
    environment:
      - NEO4J_AUTH=neo4j/password  # username: neo4j, password: password
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_connector_http_listen__address=:7474
    volumes:
      - neo4j_data:/data


volumes:
  postgres_data:
  neo4j_data:
